version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
    ports:
      - "5432:5432"
    # Uncomment for logging all SQL statements
    # command: ["postgres", "-c", "log_statement=all"]
  api:
    image: dcip-index-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
      - RPC_ENDPOINT=wss://archiver.d9network.com:40300
      - MAIN_CONTRACT_MARKET_MAKER=z8keEeLwjZFK5NS5PF6xYwTHEbm7jwpH4gBYB1JV6pDTtWg
      - MAIN_CONTRACT_CROSS_CHAIN=vNNoHwVH8af77P4s1ch14yTy7UTd8w9g2VfYA5fBExZzA7i
      - MAIN_CONTRACT_D9_USDT=uLj9DRUujbpCyK7USZY5ebGbxdtKoWvdRvGyyUsoLWDsNng
      - MAIN_CONTRACT_MERCHANT=xjyLYnZBRhYYjUKjCp8UiHnmcjHmkPfRSBxTiLLMoEwtzwp
      - MAIN_CONTRACT_BURN_MANAGER=wRGYShktZsxtKwXCCzqtLW7P1a5K2qDsaXEcRWxVYKGwH7d
      - MAIN_CONTRACT_NODE_REWARD=xqDsmMNZsCprGkjG6JPCQYysvdBs5GvudLzkXt73BbysX6D
      - LOCAL_URL=http://host.docker.internal:7000
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
  processor:
    image: dcip-index-service
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - RPC_ENDPOINT=wss://archiver.d9network.com:40300
      - MAIN_CONTRACT_MARKET_MAKER=z8keEeLwjZFK5NS5PF6xYwTHEbm7jwpH4gBYB1JV6pDTtWg
      - MAIN_CONTRACT_CROSS_CHAIN=vNNoHwVH8af77P4s1ch14yTy7UTd8w9g2VfYA5fBExZzA7i
      - MAIN_CONTRACT_D9_USDT=uLj9DRUujbpCyK7USZY5ebGbxdtKoWvdRvGyyUsoLWDsNng
      - MAIN_CONTRACT_MERCHANT=xjyLYnZBRhYYjUKjCp8UiHnmcjHmkPfRSBxTiLLMoEwtzwp
      - MAIN_CONTRACT_BURN_MANAGER=wRGYShktZsxtKwXCCzqtLW7P1a5K2qDsaXEcRWxVYKGwH7d
      - MAIN_CONTRACT_NODE_REWARD=xqDsmMNZsCprGkjG6JPCQYysvdBs5GvudLzkXt73BbysX6D
      - LOCAL_URL=http://host.docker.internal:7000
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      - db

